// <auto-generated />
namespace CaseAndMeWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class se_quita_el_campo_disositivo_id : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(se_quita_el_campo_disositivo_id));
        
        string IMigrationMetadata.Id
        {
            get { return "201810082314149_se_quita_el_campo_disositivo_id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
