// <auto-generated />
namespace CaseAndMeWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Martin20190325 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Martin20190325));
        
        string IMigrationMetadata.Id
        {
            get { return "201903260449518_Martin20190325"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
